# Generated by Django 3.2.9 on 2021-12-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=225)),
                ('model', models.CharField(max_length=225)),
                ('avg_rating', models.FloatField(blank=True, default=0, null=True)),
                ('rates_number', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
